import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';

type Activity={id:string;title:string;description?:string;startTime:string;endTime:string;location:string;ministry:string;visibility:string;status:string;rosterSummary:{totalDuties:number;confirmedDuties:number;unfilledDuties:number}};
type Newcomer={id:string;fullName:string;email?:string;phone?:string;status:string;isPotentialDuplicate:boolean;registeredAt:string};
type User={id:string;fullName:string;role:string;receptionAccess:boolean};
const fmt=(date:string)=>new Intl.DateTimeFormat('zh-CN',{timeZone:'Pacific/Auckland',month:'short',day:'numeric',weekday:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(date));
async function api(path:string,options:RequestInit={},token=''){
  const response=await fetch(`/api/v1${path}`,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})}});
  const json=await response.json(); if(!response.ok) throw new Error(json.message||'请求失败'); return json.data;
}
function App(){
  const [page,setPage]=useState<'home'|'register'|'calendar'|'scripture'|'dashboard'>('home');
  const [activities,setActivities]=useState<Activity[]>([]);const [token,setToken]=useState(sessionStorage.getItem('hcmc-token')||'');const [user,setUser]=useState<User|null>(JSON.parse(sessionStorage.getItem('hcmc-user')||'null'));const [error,setError]=useState('');
  useEffect(()=>{api('/activities').then(setActivities).catch(()=>setError('活动暂时无法加载。请确认 API 和数据库正在运行。'));},[]);
  const navigate=(p:typeof page)=>{setPage(p);setError('');window.scrollTo(0,0)};
  const logout=()=>{sessionStorage.removeItem('hcmc-token');sessionStorage.removeItem('hcmc-user');setToken('');setUser(null);navigate('home')};
  return <><header className="site-header"><button className="brand" onClick={()=>navigate('home')}><span className="brand-mark">✦</span><span>HCMC<small>汉美顿怀恩堂</small></span></button><nav aria-label="主导航"><button onClick={()=>navigate('home')}>首页</button><button onClick={()=>navigate('calendar')}>聚会日历</button><button onClick={()=>navigate('scripture')}>经文探索</button><button onClick={()=>navigate('register')}>初次来访</button><button className="nav-login" onClick={()=>navigate('dashboard')}>{user?'管理中心':'同工登录'}</button></nav></header>
  {error&&<div className="alert" role="alert">{error}</div>}
  {page==='home'&&<main className="home"><section className="hero-new"><img src="/images/hcmc-community-hero.png" alt="不同年龄的华人家庭和朋友在聚会后交流"/><div className="hero-shade"/><div className="hero-new-copy"><span className="hero-kicker">Hamilton · A church for every generation</span><h1>欢迎回家。<br/><em>Welcome home.</em></h1><p>在汉美顿相遇，在信仰里扎根，在生活中彼此同行。</p><div className="hero-actions"><button className="button-light" onClick={()=>navigate('register')}>计划你的第一次来访 <span>→</span></button><button className="button-play" onClick={()=>navigate('calendar')}><span>▶</span> 查看本周聚会</button></div></div><div className="service-ribbon"><span>本周日</span><strong>上午 10:00</strong><span>Hamilton · 地点确认后公布</span><button onClick={()=>navigate('register')}>告诉我们你会来 →</button></div></section><section className="welcome-band"><p>一个属于你的地方</p><h2>无论你来自哪里、正处在人生哪个阶段，<br/>这里都有一张为你留的椅子。</h2></section><section className="pathways"><article className="path-card path-visit"><div><span>第一次来？</span><h3>从认识彼此开始</h3><p>告诉我们你的称呼和语言偏好。接待同工会帮助你安心找到聚会、停车和适合的团契。</p></div><button onClick={()=>navigate('register')}>计划来访 <b>→</b></button></article><article className="path-card path-gather"><div><span>一起生活</span><h3>找到你的群体</h3><p>主日、团契和社区活动，让陌生人变成朋友，让每一周都有人与你同行。</p></div><button onClick={()=>navigate('calendar')}>浏览聚会 <b>→</b></button></article><article className="path-card path-grow"><div><span>继续成长</span><h3>从经文开始探索</h3><p>按章节或主题查找经文，在真实、可核对的内容里慢慢认识信仰。</p></div><button onClick={()=>navigate('scripture')}>探索经文 <b>→</b></button></article></section><section className="events-new"><div className="events-title"><span>接下来发生什么</span><h2>本周，一起来。</h2><button onClick={()=>navigate('calendar')}>查看完整日历 →</button></div><ActivityList rows={activities.slice(0,3)}/></section><section className="mission"><div className="mission-mark">H</div><div><span>我们的心意</span><h2>让离家很远的人，<br/>也能在这里找到家。</h2></div><p>我们是一群在汉美顿生活的普通人，一起敬拜、一起吃饭，也在忙碌和困难中彼此扶持。你不需要准备好，才可以来。</p></section><section className="final-invite"><span>THIS SUNDAY · 这个星期日</span><h2>来坐坐吧。</h2><p>第一次来最难的，通常只是走进门。提前告诉我们，我们会安排同工在入口等你。</p><button className="button-dark" onClick={()=>navigate('register')}>我想来看看 <span>→</span></button></section></main>}
  {page==='register'&&<main className="content-page"><div className="page-intro"><span className="eyebrow">WELCOME HOME</span><h1>很高兴认识你。</h1><p>填写下面的信息，方便我们欢迎你。联系方式只供获授权的接待同工使用；是否接受联系和活动更新由你分别决定。</p></div><Register/></main>}
  {page==='calendar'&&<main className="content-page"><div className="page-intro"><span className="eyebrow">GATHER TOGETHER</span><h1>聚会与活动</h1><p>所有时间均按新西兰汉美顿当地时间显示。</p></div><ActivityList rows={activities}/></main>}
  {page==='scripture'&&<main className="content-page"><div className="page-intro"><span className="eyebrow">SCRIPTURE EXPLORER</span><h1>从经文开始。</h1><p>输入章节如「约翰福音 3:16」，或在已导入的经文中查找关键词。完整语义问答会在语料与服务配置完成后开放。</p></div><Scripture/></main>}
  {page==='dashboard'&&<main className="content-page"><div className="page-intro"><span className="eyebrow">TEAM SPACE</span><h1>{user?`你好，${user.fullName}`:'同工登录'}</h1><p>授权同工可以处理新人跟进、活动和服事安排。</p></div>{user?<Dashboard token={token} user={user} logout={logout}/>:<Login onLogin={(t,u)=>{setToken(t);setUser(u);sessionStorage.setItem('hcmc-token',t);sessionStorage.setItem('hcmc-user',JSON.stringify(u))}}/>}</main>}
  <footer><div className="footer-brand">HCMC <span>✦</span></div><p>Hamilton Chinese Methodist Church · 汉美顿怀恩堂</p><p>欢迎每一位正在寻找归属的人。</p><small>演示项目 · 请勿输入真实个人资料</small></footer></>;
}
function ActivityList({rows}:{rows:Activity[]}){return <div className="activity-list">{rows.length?rows.map(a=><article className="activity" key={a.id}><div className="date-box"><strong>{new Intl.DateTimeFormat('en-NZ',{timeZone:'Pacific/Auckland',day:'2-digit'}).format(new Date(a.startTime))}</strong><span>{new Intl.DateTimeFormat('en-NZ',{timeZone:'Pacific/Auckland',month:'short'}).format(new Date(a.startTime)).toUpperCase()}</span></div><div><span className="item-no">{a.ministry}</span><h3>{a.title}</h3><p>{a.description||'欢迎参加我们的聚会。'}</p><small>{fmt(a.startTime)} · {a.location}</small></div><span className="activity-arrow">↗</span></article>):<div className="empty">目前没有已发布的公开活动。请稍后再来查看。</div>}</div>}
function Register(){const [done,setDone]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');const [form,setForm]=useState({fullName:'',preferredName:'',email:'',phone:'',preferredLanguage:'CHINESE',consentContact:false,subscribeUpdates:false});
  async function submit(e:React.FormEvent){e.preventDefault();setError('');setBusy(true);try{await api('/newcomers/register',{method:'POST',body:JSON.stringify({...form,email:form.email||undefined,phone:form.phone||undefined})});setDone(true)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  if(done)return <div className="form-card success"><div className="success-icon">✓</div><h2>谢谢你，期待见面！</h2><p>登记已收到。如果你选择让同工联系你，我们会在合适的时候与你联系。</p><p>聚会详情请以教会最新公告为准。</p></div>;
  return <form className="form-card" onSubmit={submit}><div className="form-title"><h2>来访登记</h2><span>约 1 分钟</span></div><label>姓名 / 称呼 *<input required maxLength={100} value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})} placeholder="你希望我们如何称呼你"/></label><div className="form-row"><label>电子邮箱<input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="name@example.com"/></label><label>电话<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="可选"/></label></div><p className="hint">邮箱或电话至少填写一项。</p><label>偏好语言<select value={form.preferredLanguage} onChange={e=>setForm({...form,preferredLanguage:e.target.value})}><option value="CHINESE">中文</option><option value="ENGLISH">English</option><option value="BILINGUAL">中英双语</option></select></label><label className="check"><input type="checkbox" checked={form.consentContact} onChange={e=>setForm({...form,consentContact:e.target.checked})}/><span>我愿意让接待同工联系我，介绍教会及聚会信息。</span></label><label className="check"><input type="checkbox" checked={form.subscribeUpdates} onChange={e=>setForm({...form,subscribeUpdates:e.target.checked})}/><span>我愿意接收未来的教会活动更新。（独立选择）</span></label><p className="privacy">资料仅用于欢迎与跟进，由获授权的同工查看。需要查阅、更正或删除资料，请联系教会管理员。</p>{error&&<p className="field-error" role="alert">{error}</p>}<button className="primary submit" disabled={busy}>{busy?'提交中…':'提交登记 ↗'}</button></form>}
function Login({onLogin}:{onLogin:(token:string,user:User)=>void}){const [email,setEmail]=useState('admin@example.com'),[password,setPassword]=useState(''),[error,setError]=useState('');async function submit(e:React.FormEvent){e.preventDefault();try{const data=await api('/auth/login',{method:'POST',body:JSON.stringify({email,password})});onLogin(data.token,data.user)}catch(e){setError((e as Error).message)}}return <form className="form-card narrow" onSubmit={submit}><label>邮箱<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>密码<input type="password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p className="field-error">{error}</p>}<button className="primary submit">登录 ↗</button><p className="hint">演示账号由 seed 脚本建立，密码由本地环境变量设置。</p></form>}
function Scripture(){const [query,setQuery]=useState(''),[results,setResults]=useState<any[]>([]),[error,setError]=useState(''),[searched,setSearched]=useState(false);async function submit(e:React.FormEvent){e.preventDefault();setError('');try{const data=await api('/scripture/search',{method:'POST',body:JSON.stringify({query})});setResults(data.results);setSearched(true)}catch(e){setError((e as Error).message)}}return <><form className="search" onSubmit={submit}><input aria-label="查找经文" value={query} onChange={e=>setQuery(e.target.value)} placeholder="试试：约翰福音 3:16"/><button className="primary">查找 ↗</button></form>{error&&<p className="field-error">{error}</p>}{searched&&<div className="results"><h2>查找结果</h2>{results.length?results.map(v=><article className="verse" key={v.id}><span className="item-no">{v.bookName} {v.chapter}:{v.verse} · {v.version}</span><p>{v.text}</p></article>):<div className="empty">未找到相关经文。演示数据库仅包含自行导入的授权语料。</div>}</div>}<div className="notice"><strong>关于经文来源</strong><p>本项目不会预装版权不明的圣经译本，也不会生成没有引用依据的信仰答案。管理员导入获授权语料后，章节与关键词查找即可使用。</p></div></>}
function Dashboard({token,user,logout}:{token:string;user:User;logout:()=>void}){const [tab,setTab]=useState<'mine'|'newcomers'|'activities'|'rosters'>('mine'),[rows,setRows]=useState<Newcomer[]>([]),[mine,setMine]=useState<any[]>([]),[activities,setActivities]=useState<Activity[]>([]),[ministries,setMinistries]=useState<{id:string;name:string}[]>([]),[volunteers,setVolunteers]=useState<{id:string;fullName:string}[]>([]),[selected,setSelected]=useState(''),[roster,setRoster]=useState<any>(null),[message,setMessage]=useState('');const canFollow=user.role==='ADMIN'||user.role==='PASTOR'||user.receptionAccess;
  async function refresh(){try{const [a,m,v,own]=await Promise.all([api('/activities',{},token),api('/ministries'),api('/users/volunteers',{},token),api('/rosters/mine',{},token)]);setActivities(a);setMinistries(m);setVolunteers(v);setMine(own);if(canFollow)setRows(await api('/newcomers',{},token))}catch(e){setMessage((e as Error).message)}}
  useEffect(()=>{refresh()},[token]);async function update(id:string,status:string){try{await api(`/newcomers/${id}/followup`,{method:'PATCH',body:JSON.stringify({status})},token);await refresh()}catch(e){setMessage((e as Error).message)}}
  async function createActivity(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);try{await api('/activities',{method:'POST',body:JSON.stringify({title:data.get('title'),startTime:new Date(String(data.get('startTime'))).toISOString(),endTime:new Date(String(data.get('endTime'))).toISOString(),location:data.get('location'),ministryId:data.get('ministryId'),visibility:data.get('visibility'),status:'PUBLISHED'})},token);setMessage('活动已创建');await refresh();e.currentTarget.reset()}catch(e){setMessage((e as Error).message)}}
  async function loadRoster(id:string){setSelected(id);try{setRoster(await api(`/rosters/activity/${id}`,{},token))}catch(e){setMessage((e as Error).message)}}
  async function addDuty(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);try{await api('/rosters/duties',{method:'POST',body:JSON.stringify({activityId:selected,name:data.get('name'),requiredCount:Number(data.get('requiredCount'))})},token);await loadRoster(selected);setMessage('岗位已添加')}catch(e){setMessage((e as Error).message)}}
  async function assign(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);try{await api('/rosters/assignments',{method:'POST',body:JSON.stringify({dutyId:data.get('dutyId'),volunteerId:data.get('volunteerId')})},token);await loadRoster(selected);setMessage('同工已安排，通知任务已建立')}catch(e){setMessage((e as Error).message)}}
  async function answer(id:string,action:'ACCEPT'|'DECLINE'){try{await api(`/rosters/assignments/${id}/respond`,{method:'POST',body:JSON.stringify({action})},token);await refresh();setMessage('回应已保存')}catch(e){setMessage((e as Error).message)}}
  return <><div className="dashboard-bar"><div className="tabs"><button className={tab==='mine'?'active':''} onClick={()=>setTab('mine')}>我的服事</button><button className={tab==='newcomers'?'active':''} onClick={()=>setTab('newcomers')}>新人跟进</button><button className={tab==='activities'?'active':''} onClick={()=>setTab('activities')}>活动管理</button><button className={tab==='rosters'?'active':''} onClick={()=>setTab('rosters')}>服事排班</button></div><button className="text-link" onClick={logout}>退出登录 ↗</button></div>{message&&<p className="alert">{message}</p>}
  {tab==='mine'&&<section className="admin-list">{mine.map(a=><article key={a.id}><div><strong>{a.activityTitle}</strong><p>{fmt(a.startTime)} · {a.dutyName} · {a.status}</p></div>{a.status==='PENDING'&&<div className="response-actions"><button onClick={()=>answer(a.id,'ACCEPT')}>接受</button><button onClick={()=>answer(a.id,'DECLINE')}>婉拒</button></div>}</article>)}{!mine.length&&<div className="empty">目前没有待处理的服事安排。</div>}</section>}
  {tab==='newcomers'&&<section>{!canFollow?<div className="empty">你的账号没有接待资料权限。</div>:<div className="admin-list">{rows.map(n=><article key={n.id}><div><strong>{n.fullName}</strong>{n.isPotentialDuplicate&&<span className="tag">可能重复</span>}<p>{n.email||n.phone||'未留联系方式'} · {fmt(n.registeredAt)}</p></div><select aria-label={`${n.fullName} 跟进状态`} value={n.status} onChange={e=>update(n.id,e.target.value)}><option value="PENDING_FOLLOWUP">待跟进</option><option value="CONTACTED">已联系</option><option value="COMPLETED">已完成</option></select></article>)}{!rows.length&&<div className="empty">暂无新人登记。</div>}</div>}</section>}
  {tab==='activities'&&<section><form className="form-card admin-form" onSubmit={createActivity}><h2>创建活动</h2><label>名称<input name="title" required/></label><div className="form-row"><label>开始<input name="startTime" type="datetime-local" required/></label><label>结束<input name="endTime" type="datetime-local" required/></label></div><div className="form-row"><label>地点<input name="location" required/></label><label>事工<select name="ministryId" required>{ministries.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label></div><label>可见范围<select name="visibility"><option value="PUBLIC">公开</option><option value="INTERNAL">内部</option></select></label><button className="primary">发布活动 ↗</button></form><div className="admin-list">{activities.map(a=><article key={a.id}><div><strong>{a.title}</strong><p>{fmt(a.startTime)} · {a.location}</p></div><span className="tag">{a.status}</span></article>)}</div></section>}
  {tab==='rosters'&&<section><label className="select-activity">选择活动<select value={selected} onChange={e=>loadRoster(e.target.value)}><option value="">请选择</option>{activities.map(a=><option key={a.id} value={a.id}>{a.title}</option>)}</select></label>{roster&&<><div className="admin-list">{roster.duties.map((d:any)=><article key={d.id}><div><strong>{d.name}</strong><p>需要 {d.requiredCount} 人</p></div><span className="tag">{roster.assignments.filter((a:any)=>a.dutyName===d.name&&a.status!=='DECLINED').length} 已安排</span></article>)}{roster.assignments.map((a:any)=><article key={a.id}><div><strong>{a.volunteerName}</strong><p>{a.dutyName}</p></div><span className="tag">{a.status}</span></article>)}</div><div className="form-row"><form className="form-card" onSubmit={addDuty}><h2>添加岗位</h2><label>岗位名称<input name="name" required/></label><label>人数<input name="requiredCount" type="number" defaultValue="1" min="1" max="20" required/></label><button className="primary">添加</button></form><form className="form-card" onSubmit={assign}><h2>安排同工</h2><label>岗位<select name="dutyId" required>{roster.duties.map((d:any)=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>同工<select name="volunteerId" required>{volunteers.map(v=><option key={v.id} value={v.id}>{v.fullName}</option>)}</select></label><button className="primary">安排</button></form></div></>}</section>}
  </>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
